import type { ipc } from '@x/shared';

// The RPC surface this server exposes over POST /rpc/{channel}. This is the
// strangler-fig migration frontier: channels move here from Electron main's
// in-process handlers group by group; anything not listed 404s (the full
// channel surface is not leaked to unauthenticated probing by name).
//
// turns:subscribe / turns:unsubscribe are deliberately absent — delta
// subscription needs connection identity, so it lives on the WebSocket
// (`{type:'subscribe', topic:'turn-deltas', turnId}`), not HTTP.
export const RPC_CHANNELS = [
  'sessions:list',
  'sessions:create',
  'sessions:get',
  'sessions:getTurn',
  'sessions:sendMessage',
  'sessions:respondToPermission',
  'sessions:respondToAskHuman',
  'sessions:stopTurn',
  'sessions:resumeTurn',
  'sessions:setTitle',
  'sessions:delete',
  'account:getRowboat',
  'workspace:getRoot',
  'workspace:exists',
  'workspace:stat',
  'workspace:readdir',
  'workspace:readFile',
  // Phase 1 (SEPARATION_PLAN.md): read-only queries. Connectors, code-mode,
  // and apps namespaces migrate in their own phases.
  'mcp:listTools',
  'runs:list',
  'runs:listByWorkDir',
  'sessions:listQueued',
  'models:list',
  'models:listForProvider',
  'models:getConfig',
  'llm:getDefaultModel',
  'rowboat:getConfig',
  'granola:getConfig',
  'knowledgeSources:getConfig',
  'onboarding:getStatus',
  'agent-schedule:getConfig',
  'agent-schedule:getState',
  'voice:getConfig',
  'live-note:get',
  'live-note:listNotes',
  'todo:get',
  'todo:getPlanner',
  'todo:getSessionConversation',
  'todo:getConversation',
  'todo:listArchived',
  'home:threads',
  'bg-task:get',
  'bg-task:list',
  'bg-task:listRunIds',
  'billing:getInfo',
  'credits:getState',
  'notifications:getSettings',
  'turnLimits:getSettings',
  'retention:getSettings',
  // Phase 2 (SEPARATION_PLAN.md): workspace & knowledge writes, todo/home/
  // deck state, settings setters. pickImage/exportCopy stay client-local
  // (native dialogs).
  'workspace:writeFile',
  'workspace:mkdir',
  'workspace:rename',
  'workspace:copy',
  'workspace:remove',
  'deck:generateOutline',
  'deck:generateSlide',
  'deck:editSlide',
  'knowledgeSources:upsert',
  'onboarding:markComplete',
  'knowledge:history',
  'knowledge:fileAtCommit',
  'knowledge:restore',
  'todo:acceptSuggestion',
  'todo:declineSuggestion',
  'todo:setPlanner',
  'todo:save',
  'todo:addItem',
  'todo:addSubItem',
  'todo:runItem',
  'todo:stopRun',
  'todo:startChat',
  'todo:chatReply',
  'todo:comment',
  'todo:clearCompleted',
  'todo:dismiss',
  'todo:teach',
  'todo:deleteArchived',
  'todo:restore',
  'home:markSeen',
  'home:setPinned',
  'home:snooze',
  'home:dismiss',
  'home:commandCenter',
  'notifications:setSettings',
  'turnLimits:setSettings',
  'retention:setSettings',
  'retention:consumeFirstRunNotice',
  // Phase 3a (SEPARATION_PLAN.md): connector data channels — verbatim lifts.
  // OAuth flow-starting channels (oauth:*, composio:*, chatgpt:signIn,
  // githubAuth:start, google-docs:pickViaManaged) relocate in Phase 3b; the
  // Slack desktop-import channels are client-machine edge capabilities and
  // stay in main permanently.
  'gmail:getImportant',
  'gmail:getEverythingElse',
  'gmail:triggerSync',
  'gmail:sendReply',
  'gmail:saveDraft',
  'gmail:deleteDraft',
  'gmail:getDrafts',
  'gmail:search',
  'gmail:getConnectionStatus',
  'gmail:getAccountEmail',
  'gmail:getAccountName',
  'gmail:setImportance',
  'gmail:setCategory',
  'gmail:archiveCategory',
  'gmail:getEmailInstructions',
  'gmail:setEmailInstructions',
  'gmail:getEmailLabels',
  'gmail:archiveThread',
  'gmail:trashThread',
  'gmail:markThreadRead',
  'gmail:downloadAttachment',
  'gmail:saveMessageHeight',
  'gmail:searchContacts',
  'chatgpt:getStatus',
  'channels:getConfig',
  'channels:setConfig',
  'channels:getStatus',
  'channels:whatsappLogout',
  'slack:getConfig',
  'slack:setConfig',
  'slack:cliStatus',
  'slack:knowledgeStatus',
  'slack:listWorkspaces',
  'slack:parseCurlAuth',
  'slack:listChannels',
  'slack:getRecentMessages',
  'google-docs:getStatus',
  'google-docs:import',
  'google-docs:refreshSnapshot',
  'google-docs:sync',
  'google-docs:getLink',
  'githubAuth:poll',
  'githubAuth:status',
  'githubAuth:signOut',
  'migration:check-composio-google',
  // Phase 3b (SEPARATION_PLAN.md): OAuth/connector flows — the loopback
  // server and orchestration live in core now; opening the browser is a
  // client capability delegated through the url-opener seam (RFC Q14 in DI
  // form; a WS capability request after the flip).
  'oauth:connect',
  'oauth:disconnect',
  'oauth:list-providers',
  'oauth:getState',
  'composio:is-configured',
  'composio:set-api-key',
  'composio:initiate-connection',
  'composio:get-connection-status',
  'composio:sync-connection',
  'composio:disconnect',
  'composio:list-connected',
  'composio:list-toolkits',
  'composio:execute-tool',
  'composio:search-tools',
  'chatgpt:signIn',
  'chatgpt:cancelSignIn',
  'chatgpt:signOut',
  'githubAuth:start',
  'google-docs:pickViaManaged',
  // Phase 4 (SEPARATION_PLAN.md): feature channels — models/llm, apps,
  // runs, live-notes, bg-tasks, schedules, search, meeting summarize, voice
  // synth, session queue/steer. Client-machine state (recording/PTT/native
  // notify, TTS streaming, permission prompts, save dialogs) stays in main.
  'mcp:executeTool',
  'runs:create',
  'runs:createMessage',
  'runs:authorizePermission',
  'runs:provideHumanInput',
  'runs:stop',
  'runs:fetch',
  'runs:delete',
  'sessions:sendOrQueueMessage',
  'sessions:editQueued',
  'sessions:removeQueued',
  'models:test',
  'llm:generate',
  'models:setProvider',
  'models:removeProvider',
  'models:updateConfig',
  'granola:setConfig',
  'apps:serverStatus',
  'apps:list',
  'apps:get',
  'apps:create',
  'apps:delete',
  'apps:setTheme',
  'apps:catalogIndex',
  'apps:catalogSearch',
  'apps:catalogStars',
  'apps:star',
  'apps:catalogDetail',
  'apps:install',
  'apps:installFromUrl',
  'apps:uninstall',
  'apps:checkUpdate',
  'apps:update',
  'apps:rollback',
  'apps:publishUpdate',
  'apps:registerExisting',
  'agent-schedule:updateAgent',
  'agent-schedule:deleteAgent',
  'search:query',
  'meeting:summarize',
  'inline-task:classifySchedule',
  'inline-task:process',
  'voice:synthesize',
  'live-note:run',
  'live-note:set',
  'live-note:setActive',
  'live-note:delete',
  'live-note:stop',
  'bg-task:run',
  'bg-task:patch',
  'bg-task:create',
  'bg-task:delete',
  'bg-task:stop',
  // Phase 7b: streaming TTS runs server-side; chunks fan out on the
  // voice:tts-chunk push channel (renderers filter by requestId).
  'voice:synthesizeStreamStart',
  'voice:synthesizeStreamCancel',
  'voice:formatDictation',
  // Phase 5 (SEPARATION_PLAN.md): code-mode & terminal — the PTY lives with
  // core now (RFC Q13: the terminal shows the machine core runs on).
  // codeMode:provisionEngine stays client-local (sender-scoped progress).
  'codeRun:resolvePermission',
  'codeMode:getConfig',
  'codeMode:setConfig',
  'codeMode:checkAgentStatus',
  'codeMode:listModelOptions',
  'codeProject:add',
  'codeProject:remove',
  'codeProject:list',
  'codeSession:create',
  'codeSession:list',
  'codeSession:update',
  'codeSession:setDone',
  'codeSession:delete',
  'codeSession:stop',
  'codeSession:gitStatus',
  'codeSession:fileDiff',
  'codeSession:readdir',
  'codeSession:readFile',
  'codeSession:mergeBack',
  'codeSession:cleanupWorktree',
  'terminal:ensure',
  'terminal:input',
  'terminal:resize',
  'terminal:dispose',

  // Phase 8b: the loopback-capable client relays OAuth callback hits here.
  'oauth:deliverLoopbackCallback',

  // Phase 9: Spaces (landed on main mid-separation) — core-coupled, so it
  // runs server-side. Client-local pieces (save dialogs, blob thumbnails)
  // stay in the Electron app.
  'spaces:listOrgs',
  'spaces:addOrg',
  'spaces:resolveInviteLink',
  'spaces:joinInvite',
  'spaces:signInOrg',
  'spaces:createOrg',
  'spaces:apexInfo',
  'spaces:removeOrg',
  'spaces:listSpaces',
  'spaces:createSpace',
  'spaces:openDirect',
  'spaces:listMembers',
  'spaces:createInvite',
  'spaces:resolveInvite',
  'spaces:acceptInvite',
  'spaces:listAssets',
  'spaces:moveAsset',
  'spaces:deleteAsset',
  'spaces:restoreAsset',
  'spaces:uploadBlob',
  'spaces:readAsset',
  'spaces:proposeChange',
  'spaces:assetHistory',
  'spaces:diff',
  'spaces:listTopics',
  'spaces:search',
  'spaces:listStream',
  'spaces:listThread',
  'spaces:linkPreview',
  'spaces:postMessage',
  'spaces:createTopic',
  'spaces:manageTopic',
  'spaces:reactToMessage',
  'spaces:deleteMessage',
  'spaces:editMessage',
  'spaces:votePoll',
  'spaces:endPoll',
  'spaces:invokeRowboat',
  'spaces:topicSession',
  'spaces:stopRowboat',
  'spaces:subscribeSpace',
  'spaces:unsubscribeSpace',
  'spaces:presence',
  'spaces:whiteboard',
  'spaces:bounceLive',
  // Notify prefs, DND and the scheduler: the mention watcher and the
  // scheduler tick run in this process (initCoreServices), and both read
  // their files through an in-memory cache — so the writes must land here
  // too, or a mute set in main is invisible until the server restarts.
  'spaces:getNotifyPrefs',
  'spaces:setNotifyPref',
  'spaces:getDnd',
  'spaces:setDnd',
  'spaces:schedule',
  'spaces:listScheduled',
  'spaces:cancelScheduled',
] as const satisfies readonly ipc.InvokeChannels[];

export type RpcChannel = (typeof RPC_CHANNELS)[number];

export function isRpcChannel(channel: string): channel is RpcChannel {
  return (RPC_CHANNELS as readonly string[]).includes(channel);
}

// One handler per exposed channel. No Electron event argument — handlers are
// transport-agnostic; connection identity is a WS concern, never an RPC one.
export type RpcHandlers = {
  [K in RpcChannel]: (
    args: ipc.IPCChannels[K]['req'],
  ) => ipc.IPCChannels[K]['res'] | Promise<ipc.IPCChannels[K]['res']>;
};
