// AUTO-GENERATED by packages/core/scripts/gen-engine-manifest.mjs — do not edit by hand.
// Regenerate after bumping the @agentclientprotocol/*-acp adapter (engine) versions.
// Maps each agent + platform to the npm tarball + integrity of its native engine.

export const ENGINE_MANIFEST = {
    "claude": {
        "version": "0.3.232",
        "platforms": {
            "darwin-arm64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-darwin-arm64",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-arm64/-/claude-agent-sdk-darwin-arm64-0.3.232.tgz",
                "integrity": "sha512-+/4PX+dwmQAjlOlooocwa3kClulZfMo133xQH3LYDlK7D5bzze16lwlDGPVAYGEarpvXg7G5JK8QjfWAJ2HYbg=="
            },
            "darwin-x64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-darwin-x64",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-darwin-x64/-/claude-agent-sdk-darwin-x64-0.3.232.tgz",
                "integrity": "sha512-EHZ1Y3aGyZ2mFZ6QLR1bM3/HiIn2cLrPjU+k3/oCIW6omJFodfzf410aWjDPSnMj7CE4d6t7MSjBWekMUbcv0g=="
            },
            "linux-x64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-x64",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64/-/claude-agent-sdk-linux-x64-0.3.232.tgz",
                "integrity": "sha512-6Px1xDiwQyLkSxwRQ34/kPA8WMXQ2rHYGkwockND7+9yMw+ShI3AfLkyi9G7JtJHObWFT6B82eSHjDS/Fy+9hQ=="
            },
            "linux-arm64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-arm64",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64/-/claude-agent-sdk-linux-arm64-0.3.232.tgz",
                "integrity": "sha512-wW2opwA5s7gLghjU6B2ADMAtoc7bAZMevUzi4g+1PXMJ8MGcPvbnx92EDYJrVDcZmAl1+fz19XyPsaShlisTzw=="
            },
            "linux-x64-musl": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-x64-musl",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-x64-musl/-/claude-agent-sdk-linux-x64-musl-0.3.232.tgz",
                "integrity": "sha512-L1x2ge9NpXMLTczmT44TKPQ88PHE+gsCakQMVEOa8rXFvfBoqvcpxM0DT8wrqYWUHhQEYR8NXxQTP9a1NVRj8Q=="
            },
            "linux-arm64-musl": {
                "pkg": "@anthropic-ai/claude-agent-sdk-linux-arm64-musl",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-linux-arm64-musl/-/claude-agent-sdk-linux-arm64-musl-0.3.232.tgz",
                "integrity": "sha512-XkLcb9UT/l42Rtw7KBApzgxUe/kwoWJ9KCPcVEnYojzIvVR+AwBCl/QReNU5+6c72w48dYBMmLebI64gQbN0tg=="
            },
            "win32-x64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-win32-x64",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-x64/-/claude-agent-sdk-win32-x64-0.3.232.tgz",
                "integrity": "sha512-Hc/9uy1BI9mqKVyB1b/zoUnm3MFgtVNzQY6p5zgaq9DaIjCKDpR4a4L1aDZM4lMqUcWFMZM+u7juOhh+m39NBQ=="
            },
            "win32-arm64": {
                "pkg": "@anthropic-ai/claude-agent-sdk-win32-arm64",
                "pkgVersion": "0.3.232",
                "tarball": "https://registry.npmjs.org/@anthropic-ai/claude-agent-sdk-win32-arm64/-/claude-agent-sdk-win32-arm64-0.3.232.tgz",
                "integrity": "sha512-fDiuwL5dm1elOy7fNp4Qmdor8so4R8npj2pUGQA1G/xKfJhaK236aTWezvZid3L/O7cRdFeN9IVofOAlWLQcsw=="
            }
        }
    },
    "codex": {
        "version": "0.147.0",
        "platforms": {
            "darwin-arm64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.147.0-darwin-arm64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.147.0-darwin-arm64.tgz",
                "integrity": "sha512-BEUVkiOW7kLcRyrMLfAr/h9wF8sRVJyZDy6OHtVn6QGDXiv3BvAZVTY1Pu9xF7KdIdkYXbp4uayN0aDQQaAUJw=="
            },
            "darwin-x64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.147.0-darwin-x64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.147.0-darwin-x64.tgz",
                "integrity": "sha512-Tb8McE5SvJIH0Vs5R6sq7u+quiC931yan2KOOl6km1OdZ82+Wi7eF5XrSFPs5CF7xCgoIK4Vs+byMbT5hN+ZUw=="
            },
            "linux-x64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.147.0-linux-x64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.147.0-linux-x64.tgz",
                "integrity": "sha512-0W9MBxPpWW0cSkNqrTDN2jR7rzzT7oNMhQY5446lT2Lw5cz5yhDTck4Va9rjkQEm+HlFzP/dmEMSZbXfJsINmw=="
            },
            "linux-arm64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.147.0-linux-arm64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.147.0-linux-arm64.tgz",
                "integrity": "sha512-SLC1JXw2TYfr/c3HhrJubyyLelq7vTOLWVmiThFA+z0+WgzCPmaseJ/kzDD3Gge/TO7fCnnj7UcPmC0d2c8XAg=="
            },
            "win32-x64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.147.0-win32-x64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.147.0-win32-x64.tgz",
                "integrity": "sha512-oT7Ss5fAPf2fiWE9QNURqZcQGAAawSVxmIUdgPzckq4KFZAM+pRz9JbM4Rr498CjtbNgTOjWvDJ+DXvIBSfOPA=="
            },
            "win32-arm64": {
                "pkg": "@openai/codex",
                "pkgVersion": "0.147.0-win32-arm64",
                "tarball": "https://registry.npmjs.org/@openai/codex/-/codex-0.147.0-win32-arm64.tgz",
                "integrity": "sha512-e2ZstJ8zT8Rm1nvR7CUVO+Gr3cTChE41+VfOzGhynzDXEoW0wfbjUQbc2bWbh1arG94LMm4y3dqBtUIbSrfeGA=="
            }
        }
    }
} as const;
